import { NextApiRequest } from "next";

export function createNextRequestMock(
  body?: any,
  customData?: Partial<NextApiRequest>
): NextApiRequest {
  return {
    aborted: false,
    body,
    complete: false,
    connection: {} as any,
    cookies: {},
    destroyed: false,
    env: {},
    headers: {},
    httpVersion: "",
    httpVersionMajor: 0,
    httpVersionMinor: 0,
    query: {},
    rawHeaders: [],
    rawTrailers: [],
    readable: false,
    readableEncoding: null,
    readableEnded: false,
    readableFlowing: null,
    readableHighWaterMark: 0,
    readableLength: 0,
    readableObjectMode: false,
    setTimeout: jest.fn(),
    socket: {} as any,
    trailers: {},
    [Symbol.asyncIterator](): any {},
    _destroy: jest.fn(),
    _read: jest.fn(),
    addListener: jest.fn(),
    destroy: jest.fn(),
    emit: jest.fn(),
    eventNames: jest.fn(),
    getMaxListeners: jest.fn(),
    isPaused: jest.fn(),
    listenerCount: jest.fn(),
    listeners: jest.fn(),
    off: jest.fn(),
    on: jest.fn(),
    once: jest.fn(),
    pause: jest.fn(),
    pipe: jest.fn(),
    prependListener: jest.fn(),
    prependOnceListener: jest.fn(),
    push: jest.fn(),
    rawListeners: jest.fn(),
    read: jest.fn(),
    removeAllListeners: jest.fn(),
    removeListener: jest.fn(),
    resume: jest.fn(),
    setEncoding: jest.fn(),
    setMaxListeners: jest.fn(),
    unpipe: jest.fn(),
    unshift: jest.fn(),
    wrap: jest.fn(),
    ...customData,
  };
}
