export enum GlobalWizardStates {
  LOGIN = "LOGIN",
  REGISTER = "REGISTER",
  REGISTER_ACTIVATE = "REGISTER_ACTIVATE",
  FORGOT_PASSWORD = "FORGOT_PASSWORD",
  FORGOT_PASSWORD_ACTIVATE = "FORGOT_PASSWORD_ACTIVATE",
}
